package tela;

import apoio.ConexaoBD;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(true);

        setLocationRelativeTo(null);
        setTitle("Aplicação");

        // Criar um JPanel personalizado para o fundo em gradiente
        JPanel backgroundPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                // Criar um gradiente linear vertical para o fundo
                GradientPaint gradient = new GradientPaint(0, 0, new Color(0xADD8E6), 0, getHeight(), new Color(0x00008B));
                Graphics2D g2d = (Graphics2D) g;
                g2d.setPaint(gradient);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };

        // Adicionar um ouvinte de evento para redimensionar o backgroundPanel
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                backgroundPanel.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
            }
        });

        // Adicionar o JPanel personalizado como fundo diretamente ao JDesktopPane
        jDesktopPane1.add(backgroundPanel, JLayeredPane.DEFAULT_LAYER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuEndereco = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuPedido = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuClientesRel = new javax.swing.JMenuItem();
        jMenuProdutosRel = new javax.swing.JMenuItem();
        jMenuPedidoData = new javax.swing.JMenuItem();
        jMenuPedidoCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        jMenuEndereco.setText("Endereço");
        jMenuEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEnderecoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEndereco);

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCliente);

        jMenuProduto.setText("Produto");
        jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuProduto);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Movimentações");

        jMenuPedido.setText("Pedido");
        jMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPedido);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        jMenuClientesRel.setText("Clientes");
        jMenuClientesRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesRelActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuClientesRel);

        jMenuProdutosRel.setText("Produtos");
        jMenuProdutosRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutosRelActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuProdutosRel);

        jMenuPedidoData.setText("Pedidos por data");
        jMenuPedidoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidoDataActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuPedidoData);

        jMenuPedidoCliente.setText("Pedidos por cliente");
        jMenuPedidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidoClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuPedidoCliente);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Ajuda");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEnderecoActionPerformed
        IfrEndereco ifrEndereco = new IfrEndereco();
        jDesktopPane1.add(ifrEndereco);
        ifrEndereco.setLocation((jDesktopPane1.getWidth() - ifrEndereco.getWidth()) / 2, (jDesktopPane1.getHeight() - ifrEndereco.getHeight()) / 2);
        ifrEndereco.setVisible(true);

    }//GEN-LAST:event_jMenuEnderecoActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        IfrCliente ifrCliente = new IfrCliente();
        jDesktopPane1.add(ifrCliente);
        ifrCliente.setLocation((jDesktopPane1.getWidth() - ifrCliente.getWidth()) / 2, (jDesktopPane1.getHeight() - ifrCliente.getHeight()) / 2);
        ifrCliente.setVisible(true);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoActionPerformed
        IfrProduto ifrProduto = new IfrProduto();
        jDesktopPane1.add(ifrProduto);
        ifrProduto.setLocation((jDesktopPane1.getWidth() - ifrProduto.getWidth()) / 2, (jDesktopPane1.getHeight() - ifrProduto.getHeight()) / 2);
        ifrProduto.setVisible(true);
    }//GEN-LAST:event_jMenuProdutoActionPerformed

    private void jMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidoActionPerformed
        IfrPedido ifrPedido = new IfrPedido();
        jDesktopPane1.add(ifrPedido);
        ifrPedido.setLocation((jDesktopPane1.getWidth() - ifrPedido.getWidth()) / 2, (jDesktopPane1.getHeight() - ifrPedido.getHeight()) / 2);
        ifrPedido.setVisible(true);
    }//GEN-LAST:event_jMenuPedidoActionPerformed

    private void jMenuClientesRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesRelActionPerformed
        try {
            // Compila o relatório
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/listagem_cli.jrxml"));

            // Mapeia campos de parâmetros para o relatório
            Map parametros = new HashMap();

            // Executa relatório
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoBD.getInstance().getConnection());

            // Exibe resultado em vídeo
            this.setAlwaysOnTop(false);
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
        }
    }//GEN-LAST:event_jMenuClientesRelActionPerformed

    private void jMenuProdutosRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutosRelActionPerformed
        try {
            // Compila o relatório
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/listagem_prod.jrxml"));

            // Mapeia campos de parâmetros para o relatório
            Map parametros = new HashMap();

            // Executa relatório
            JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ConexaoBD.getInstance().getConnection());

            // Exibe resultado em vídeo
            this.setAlwaysOnTop(false);
            JasperViewer.viewReport(impressao, false);
        } catch (Exception e) {
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
        }
    }//GEN-LAST:event_jMenuProdutosRelActionPerformed

    private void jMenuPedidoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidoDataActionPerformed
        this.setAlwaysOnTop(false);

        DlgDataPedido dlgDataPedido = new DlgDataPedido(this, true);
        dlgDataPedido.setVisible(true);
    }//GEN-LAST:event_jMenuPedidoDataActionPerformed

    private void jMenuPedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidoClienteActionPerformed
        this.setAlwaysOnTop(false);

        DlgClientePedido dlgClientePedido = new DlgClientePedido(this, true);
        dlgClientePedido.setVisible(true);
    }//GEN-LAST:event_jMenuPedidoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuClientesRel;
    private javax.swing.JMenuItem jMenuEndereco;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuPedido;
    private javax.swing.JMenuItem jMenuPedidoCliente;
    private javax.swing.JMenuItem jMenuPedidoData;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenuItem jMenuProdutosRel;
    // End of variables declaration//GEN-END:variables
}
