package tela;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.Validar;
import dao.ClienteDAO;
import entidade.Cliente;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author felip
 */
public class IfrCliente extends javax.swing.JInternalFrame {

    int idCliente = 0;

    Border erro = BorderFactory.createEtchedBorder(Color.red, Color.red);
    Border normal = BorderFactory.createEtchedBorder(null, null);

    /**
     * Creates new form IfrCliente
     */
    public IfrCliente() {
        initComponents();
        setTitle("Clientes");

        new ClienteDAO().popularTabela(tblCliente, "");
        new CombosDAO().popularCombo("endereco", cmbEndereco);

        Formatacao.formatarCpf(tffCpfCliente);
        Formatacao.formatarCelular(tffTelefoneCliente);

        this.getContentPane().setBackground(new Color(245, 255, 250));
        jPanel1.setBackground(new Color(240, 248, 255));
        jPanel2.setBackground(new Color(240, 248, 255));
        
        //this.setContentPane(new GradientPanel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tfdPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdNomeCliente = new javax.swing.JTextField();
        cmbEndereco = new javax.swing.JComboBox<>();
        tffCpfCliente = new javax.swing.JFormattedTextField();
        tffTelefoneCliente = new javax.swing.JFormattedTextField();
        tfdEmailCliente = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCliente);

        jLabel3.setText("Busca");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfdPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jLabel1.setText("Nome:");

        jLabel2.setText("E-mail:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("CPF:");

        jLabel6.setText("Endereço:");

        tfdNomeCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfdNomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdNomeClienteFocusLost(evt);
            }
        });

        cmbEndereco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tffCpfCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tffCpfCliente.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        tffCpfCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCpfClienteFocusLost(evt);
            }
        });

        tffTelefoneCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tffTelefoneCliente.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        tffTelefoneCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffTelefoneClienteFocusLost(evt);
            }
        });

        tfdEmailCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfdEmailCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEmailClienteFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdNomeCliente)
                    .addComponent(cmbEndereco, 0, 510, Short.MAX_VALUE)
                    .addComponent(tffCpfCliente)
                    .addComponent(tffTelefoneCliente)
                    .addComponent(tfdEmailCliente))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tffTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tffCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel2);

        btnFechar.setText("Fechar");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 254, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new ClienteDAO().popularTabela(tblCliente, tfdPesquisar.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        btnFechar.setBackground(new Color(255, 100, 100));
    }//GEN-LAST:event_btnFecharMouseEntered

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        Color corPadrao = UIManager.getColor("Button.background");
        btnFechar.setBackground(corPadrao);
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String nomeCliente = tfdNomeCliente.getText();
        String emailCliente = tfdEmailCliente.getText();
        String telefoneCliente = tffTelefoneCliente.getText();
        String cpfCliente = tffCpfCliente.getText();

        ComboItem ci = (ComboItem) cmbEndereco.getSelectedItem();
        int endereco_idCliente = ci.getCodigo();
        //String enderecoCliente = ci.getDescricao();

        if (!Validar.validarNome(nomeCliente)) {
            JOptionPane.showMessageDialog(this, "Nome inválido!");
            return; // Sai do método sem salvar
        }

        if (!Validar.validarEmail(emailCliente)) {
            JOptionPane.showMessageDialog(this, "Email inválido!");
            return; // Sai do método sem salvar
        }

        if (!Validar.validarCelular(telefoneCliente)) {
            JOptionPane.showMessageDialog(this, "Telefone inválido");
            return;
        }

        if (!Validar.validarCPF(cpfCliente)) {
            JOptionPane.showMessageDialog(this, "CPF inválido!");
            return;
        }

        if (endereco_idCliente == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um endereço!");
            return;
        }

        Cliente cliente = new Cliente();
        cliente.setId(idCliente);
        cliente.setNome(nomeCliente);
        cliente.setEmail(emailCliente);
        cliente.setTelefone(telefoneCliente);
        cliente.setCpf(cpfCliente);
        cliente.setEndereco_id(endereco_idCliente);

        ClienteDAO clienteDao = new ClienteDAO();

        if (idCliente == 0) {
            if (clienteDao.salvar(cliente) == null) {
                tfdNomeCliente.setText("");
                tfdEmailCliente.setText("");
                tffTelefoneCliente.setText("");
                tffCpfCliente.setText("");
                cmbEndereco.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                new ClienteDAO().popularTabela(tblCliente, "");

                tfdNomeCliente.requestFocus();

            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        } else {
            if (clienteDao.atualizar(cliente) == null) {
                tfdNomeCliente.setText("");
                tfdEmailCliente.setText("");
                tffTelefoneCliente.setText("");
                tffCpfCliente.setText("");
                cmbEndereco.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Registro editado com sucesso!");
                new ClienteDAO().popularTabela(tblCliente, "");

                tfdNomeCliente.requestFocus();

            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao editar registro!");
            }
        }

        idCliente = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idTabela = String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0));

        idCliente = Integer.parseInt(idTabela);

        Cliente cliente = new ClienteDAO().consultarId(idCliente);

        if (cliente != null) {
            jTabbedPane1.setSelectedIndex(1);

            tfdNomeCliente.setText(cliente.getNome());
            tfdEmailCliente.setText(cliente.getEmail());
            tffTelefoneCliente.setText(cliente.getTelefone());
            tffCpfCliente.setText(cliente.getCpf());

            int enderecoId = cliente.getEndereco_id();

            for (int i = 0; i < cmbEndereco.getItemCount(); i++) {
                Object itemObj = cmbEndereco.getItemAt(i);
                if (itemObj instanceof ComboItem) {
                    ComboItem item = (ComboItem) itemObj;
                    if (item.getCodigo() == enderecoId) {
                        cmbEndereco.setSelectedIndex(i);
                        break;
                    }
                }
            }

            tfdNomeCliente.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do cliente não encontrado! ");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idTabela = String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0));

        idCliente = Integer.parseInt(idTabela);

        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja excluir o registro selecionado?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            // Caso o usuário confirme a exclusão
            if (new ClienteDAO().excluir(idCliente) == null) {
                JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");

                new ClienteDAO().popularTabela(tblCliente, "");
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao excluir registro!");
            }
        }

        idCliente = 0;
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tffCpfClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCpfClienteFocusLost

        if (!Validar.validarCPF(tffCpfCliente.getText())) {
            tffCpfCliente.setBorder(erro);
        } else {
            tffCpfCliente.setBorder(normal);
        }
    }//GEN-LAST:event_tffCpfClienteFocusLost

    private void tffTelefoneClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffTelefoneClienteFocusLost

        if (!Validar.validarCelular(tffTelefoneCliente.getText())) {
            tffTelefoneCliente.setBorder(erro);
        } else {
            tffTelefoneCliente.setBorder(normal);
        }
    }//GEN-LAST:event_tffTelefoneClienteFocusLost

    private void tfdEmailClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEmailClienteFocusLost

        if (!Validar.validarEmail(tfdEmailCliente.getText())) {
            tfdEmailCliente.setBorder(erro);
        } else {
            tfdEmailCliente.setBorder(normal);
        }
    }//GEN-LAST:event_tfdEmailClienteFocusLost

    private void tfdNomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdNomeClienteFocusLost

        if (!Validar.validarNome(tfdNomeCliente.getText())) {
            tfdNomeCliente.setBorder(erro);
        } else {
            tfdNomeCliente.setBorder(normal);
        }
    }//GEN-LAST:event_tfdNomeClienteFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField tfdEmailCliente;
    private javax.swing.JTextField tfdNomeCliente;
    private javax.swing.JTextField tfdPesquisar;
    private javax.swing.JFormattedTextField tffCpfCliente;
    private javax.swing.JFormattedTextField tffTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
